version: '3.8'
name: ai_wallpapers_backend

services:
    database:
        image: postgres
        ports:
            - "127.0.0.1:5432:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: qwerty12
            POSTGRES_DB: db_app
        volumes:
            - ./postgres-data:/var/lib/postgresql/data
